const teams = [
  { id: 'arsenal', name: 'Arsenal', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/330px-Arsenal_FC.svg.png' },
  { id: 'aston-villa', name: 'Aston Villa', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Aston_Villa_FC_new_crest.svg/330px-Aston_Villa_FC_new_crest.svg.png' },
  { id: 'bournemouth', name: 'Bournemouth', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Bournemouth_FC_logo.png' },
  { id: 'brentford', name: 'Brentford', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/330px-Brentford_FC_crest.svg.png' },
  { id: 'brighton', name: 'Brighton', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/0/0e/BrightonVFA.png' },
  { id: 'chelsea', name: 'Chelsea', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/330px-Chelsea_FC.svg.png' },
  { id: 'crystal-palace', name: 'Crystal Palace', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Crystal_Palace_FC_logo_%282022%29.svg/330px-Crystal_Palace_FC_logo_%282022%29.svg.png' },
  { id: 'everton', name: 'Everton', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/330px-Everton_FC_logo.svg.png' },
  { id: 'fulham', name: 'Fulham', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Fulham_FC_%28shield%29.svg/330px-Fulham_FC_%28shield%29.svg.png' },
  { id: 'ipswich', name: 'Ipswich Town', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Ipswich_Town.svg/330px-Ipswich_Town.svg.png' },
  { id: 'leicester', name: 'Leicester City', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/330px-Leicester_City_crest.svg.png' },
  { id: 'liverpool', name: 'Liverpool', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/330px-Liverpool_FC.svg.png' },
  { id: 'mancity', name: 'Manchester City', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/330px-Manchester_City_FC_badge.svg.png' },
  { id: 'manutd', name: 'Manchester United', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/330px-Manchester_United_FC_crest.svg.png' },
  { id: 'newcastle', name: 'Newcastle United', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/330px-Newcastle_United_Logo.svg.png' },
  { id: 'nottingham', name: 'Nottingham Forest', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Nottingham_Forest_F.C._logo.svg/330px-Nottingham_Forest_F.C._logo.svg.png' },
  { id: 'southampton', name: 'Southampton', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/FC_Southampton.svg/330px-FC_Southampton.svg.png' },
  { id: 'tottenham', name: 'Tottenham', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/330px-Tottenham_Hotspur.svg.png' },
  { id: 'westham', name: 'West Ham United', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/330px-West_Ham_United_FC_logo.svg.png' },
  { id: 'wolves', name: 'Wolves', league: 'Premier League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Wolverhampton_Wanderers_FC_crest.svg/330px-Wolverhampton_Wanderers_FC_crest.svg.png' },
  { id: 'alaves', name: 'Alaves', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Al_Ahed_FC_logo_%282023%29.svg/330px-Al_Ahed_FC_logo_%282023%29.svg.png' },
  { id: 'athletic', name: 'Athletic Club', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Athletic_Club_%28Minas_Gerais%29.svg/330px-Athletic_Club_%28Minas_Gerais%29.svg.png' },
  { id: 'atletico', name: 'Atletico Madrid', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Atl%C3%A9tico_Madrid_Europa_League_2010_Pennant.jpg/330px-Atl%C3%A9tico_Madrid_Europa_League_2010_Pennant.jpg' },
  { id: 'barcelona', name: 'Barcelona', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/330px-FC_Barcelona_%28crest%29.svg.png' },
  { id: 'betis', name: 'Real Betis', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_betis_logo.svg/330px-Real_betis_logo.svg.png' },
  { id: 'celta', name: 'Celta Vigo', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/RC_Celta_de_Vigo_logo.svg/330px-RC_Celta_de_Vigo_logo.svg.png' },
  { id: 'espanyol', name: 'Espanyol', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/92/RCD_Espanyol_crest.svg/330px-RCD_Espanyol_crest.svg.png' },
  { id: 'getafe', name: 'Getafe', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Getafe_logo.svg/330px-Getafe_logo.svg.png' },
  { id: 'girona', name: 'Girona', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Girona_FC_Logo.svg/330px-Girona_FC_Logo.svg.png' },
  { id: 'las-palmas', name: 'Las Palmas', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/SpanishCongressDistricts%28LasPalmas%29.png/330px-SpanishCongressDistricts%28LasPalmas%29.png' },
  { id: 'leganes', name: 'Leganes', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/57/Le_Mans_FC_logo.svg/330px-Le_Mans_FC_logo.svg.png' },
  { id: 'mallorca', name: 'Mallorca', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/48/The_Mallorca_Files.JPG/330px-The_Mallorca_Files.JPG' },
  { id: 'osasuna', name: 'Osasuna', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/38/CA_Osasuna_2024_crest.svg/330px-CA_Osasuna_2024_crest.svg.png' },
  { id: 'rayo', name: 'Rayo Vallecano', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d8/Rayo_Vallecano_logo.svg/330px-Rayo_Vallecano_logo.svg.png' },
  { id: 'realmadrid', name: 'Real Madrid', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/RM_first_king_cup.jpg/330px-RM_first_king_cup.jpg' },
  { id: 'realsociedad', name: 'Real Sociedad', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Real_Sociedad_logo.svg/330px-Real_Sociedad_logo.svg.png' },
  { id: 'sevilla', name: 'Sevilla', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Lolita_Sevilla_en_1973.jpg/330px-Lolita_Sevilla_en_1973.jpg' },
  { id: 'valencia', name: 'Valencia', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Malvarrosa_Beach%2C_Valencia%2C_Spain_%2829812271043%29.jpg/330px-Malvarrosa_Beach%2C_Valencia%2C_Spain_%2829812271043%29.jpg' },
  { id: 'valladolid', name: 'Valladolid', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Canal_de_Castilla.jpg/330px-Canal_de_Castilla.jpg' },
  { id: 'villarreal', name: 'Villarreal', league: 'La Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Villarreal_CF_logo-en.svg/330px-Villarreal_CF_logo-en.svg.png' },
  { id: 'augsburg', name: 'Augsburg', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/FC_Augsburg_logo.svg/330px-FC_Augsburg_logo.svg.png' },
  { id: 'bayern', name: 'Bayern Munich', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg/330px-FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg.png' },
  { id: 'bochum', name: 'Bochum', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/VfL_Bochum_logo.svg/330px-VfL_Bochum_logo.svg.png' },
  { id: 'dortmund', name: 'Borussia Dortmund', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/330px-Borussia_Dortmund_logo.svg.png' },
  { id: 'frankfurt', name: 'Eintracht Frankfurt', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Eintracht_Frankfurt_crest.svg/330px-Eintracht_Frankfurt_crest.svg.png' },
  { id: 'freiburg', name: 'Freiburg', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Freiburg_im_Breisgau_M%C3%BCnster.jpg/330px-Freiburg_im_Breisgau_M%C3%BCnster.jpg' },
  { id: 'heidenheim', name: 'Heidenheim', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Heidenheim_von_Osten_gesehen.jpg/330px-Heidenheim_von_Osten_gesehen.jpg' },
  { id: 'hoffenheim', name: 'Hoffenheim', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Logo_TSG_Hoffenheim.svg/330px-Logo_TSG_Hoffenheim.svg.png' },
  { id: 'holstein-kiel', name: 'Holstein Kiel', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Holstein_Kiel_Logo.svg/330px-Holstein_Kiel_Logo.svg.png' },
  { id: 'leverkusen', name: 'Bayer Leverkusen', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Bayer_04_Leverkusen_logo.svg/330px-Bayer_04_Leverkusen_logo.svg.png' },
  { id: 'leipzig', name: 'RB Leipzig', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/330px-RB_Leipzig_2014_logo.svg.png' },
  { id: 'mainz', name: 'Mainz 05', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/1._FSV_Mainz_05_logo.svg/330px-1._FSV_Mainz_05_logo.svg.png' },
  { id: 'monchengladbach', name: 'Borussia Monchengladbach', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Borussia_M%C3%B6nchengladbach_logo.svg/330px-Borussia_M%C3%B6nchengladbach_logo.svg.png' },
  { id: 'st-pauli', name: 'St. Pauli', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/FC_St._Pauli_logo_%282018%29.svg/330px-FC_St._Pauli_logo_%282018%29.svg.png' },
  { id: 'stuttgart', name: 'Stuttgart', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/VfB_Stuttgart_1893_Logo.svg/330px-VfB_Stuttgart_1893_Logo.svg.png' },
  { id: 'union-berlin', name: 'Union Berlin', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/1._FC_Union_Berlin_Logo.svg/330px-1._FC_Union_Berlin_Logo.svg.png' },
  { id: 'werder', name: 'Werder Bremen', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/SV-Werder-Bremen-Logo.svg/330px-SV-Werder-Bremen-Logo.svg.png' },
  { id: 'wolfsburg', name: 'Wolfsburg', league: 'Bundesliga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/VfL_Wolfsburg_Logo.svg/330px-VfL_Wolfsburg_Logo.svg.png' },
  { id: 'ajax', name: 'Ajax', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/01/AFC_Ajax_crest.svg/330px-AFC_Ajax_crest.svg.png' },
  { id: 'az', name: 'AZ Alkmaar', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/AZ_Alkmaar.svg/330px-AZ_Alkmaar.svg.png' },
  { id: 'feyenoord', name: 'Feyenoord', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Feyenoord_logo_since_2024.svg/330px-Feyenoord_logo_since_2024.svg.png' },
  { id: 'psv', name: 'PSV', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/PSV_Eindhoven.svg/330px-PSV_Eindhoven.svg.png' },
  { id: 'twente', name: 'Twente', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/FC_Twente.svg/330px-FC_Twente.svg.png' },
  { id: 'utrecht', name: 'Utrecht', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Logo_FC_Utrecht.svg/330px-Logo_FC_Utrecht.svg.png' },
  { id: 'go-ahead', name: 'Go Ahead Eagles', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Go_Ahead_Eagles_logo.svg/330px-Go_Ahead_Eagles_logo.svg.png' },
  { id: 'heerenveen', name: 'Heerenveen', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/SC_Heerenveen_logo.svg/330px-SC_Heerenveen_logo.svg.png' },
  { id: 'nec', name: 'NEC Nijmegen', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LogoN.E.C.png/330px-LogoN.E.C.png' },
  { id: 'sparta', name: 'Sparta Rotterdam', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Sparta_Rotterdam_logo.svg/330px-Sparta_Rotterdam_logo.svg.png' },
  { id: 'fortuna', name: 'Fortuna Sittard', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ef/Fortuna_Sittard_Logo.svg/330px-Fortuna_Sittard_Logo.svg.png' },
  { id: 'pec-zwolle', name: 'PEC Zwolle', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/PEC_Zwolle_logo.svg/330px-PEC_Zwolle_logo.svg.png' },
  { id: 'heracles', name: 'Heracles Almelo', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Heracles_Almelo_logo.svg/330px-Heracles_Almelo_logo.svg.png' },
  { id: 'groningen', name: 'Groningen', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/FC_Groningen_logo.svg/330px-FC_Groningen_logo.svg.png' },
  { id: 'nac', name: 'NAC Breda', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Logo_NAC_Breda.svg/330px-Logo_NAC_Breda.svg.png' },
  { id: 'rkc', name: 'RKC Waalwijk', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/RKC_Waalwijk_logo.svg/330px-RKC_Waalwijk_logo.svg.png' },
  { id: 'almere', name: 'Almere City', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/8/86/Almere_City_FC_logo.PNG' },
  { id: 'willem-ii', name: 'Willem II', league: 'Eredivisie', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Willem_II_logo.svg/330px-Willem_II_logo.svg.png' },
  { id: 'benfica', name: 'Benfica', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/SL_Benfica_logo.svg/330px-SL_Benfica_logo.svg.png' },
  { id: 'porto', name: 'Porto', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/FC_Porto.svg/330px-FC_Porto.svg.png' },
  { id: 'sporting', name: 'Sporting CP', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/95/Sporting_CP_crest.svg/330px-Sporting_CP_crest.svg.png' },
  { id: 'braga', name: 'Braga', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/79/S.C._Braga_logo.svg/330px-S.C._Braga_logo.svg.png' },
  { id: 'vitoria-sc', name: 'Vitoria SC', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Vit%C3%B3ria_Guimar%C3%A3es.svg/330px-Vit%C3%B3ria_Guimar%C3%A3es.svg.png' },
  { id: 'boavista', name: 'Boavista', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Boavista_F.C._logo.svg/330px-Boavista_F.C._logo.svg.png' },
  { id: 'famalicao', name: 'Famalicao', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0e/F.C._Famalic%C3%A3o_logo.svg/330px-F.C._Famalic%C3%A3o_logo.svg.png' },
  { id: 'estoril', name: 'Estoril', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/94/GD_Estoril_Praia_logo.svg/330px-GD_Estoril_Praia_logo.svg.png' },
  { id: 'moreirense', name: 'Moreirense', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1b/Moreirense_Futebol_Clube_logo.svg/330px-Moreirense_Futebol_Clube_logo.svg.png' },
  { id: 'rio-ave', name: 'Rio Ave', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Rio_Ave_FC_logo.svg/330px-Rio_Ave_FC_logo.svg.png' },
  { id: 'gil-vicente', name: 'Gil Vicente', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/8/8f/Gil_Vicente_F.C.png' },
  { id: 'arouca', name: 'Arouca', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/F.C._Arouca_logo.svg/330px-F.C._Arouca_logo.svg.png' },
  { id: 'nacional', name: 'Nacional', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/90/C.D._Nacional_logo.svg/330px-C.D._Nacional_logo.svg.png' },
  { id: 'farense', name: 'Farense', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/d/d1/S.C._Farense.png' },
  { id: 'santa-clara', name: 'Santa Clara', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/37/C.D._Santa_Clara_logo.svg/330px-C.D._Santa_Clara_logo.svg.png' },
  { id: 'casa-pia', name: 'Casa Pia', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/4/4d/Casa_Pia_A.C._logo.png' },
  { id: 'estrela', name: 'Estrela Amadora', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/S%C3%ADmbolo_Estrela_da_Amadora.svg/330px-S%C3%ADmbolo_Estrela_da_Amadora.svg.png' },
  { id: 'avs', name: 'AVS', league: 'Primeira Liga', logo: 'https://upload.wikimedia.org/wikipedia/en/4/42/AVS_Futebol_SAD_logo.png' },
  { id: 'psg', name: 'PSG', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/330px-Paris_Saint-Germain_F.C..svg.png' },
  { id: 'marseille', name: 'Marseille', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Olympique_Marseille_logo.svg/330px-Olympique_Marseille_logo.svg.png' },
  { id: 'lyon', name: 'Lyon', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/Olympique_Lyonnais_logo.svg/330px-Olympique_Lyonnais_logo.svg.png' },
  { id: 'monaco', name: 'Monaco', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/LogoASMonacoFC2021.svg/330px-LogoASMonacoFC2021.svg.png' },
  { id: 'lille', name: 'Lille', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Lille_OSC_2018_logo.svg/330px-Lille_OSC_2018_logo.svg.png' },
  { id: 'nice', name: 'Nice', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/OGC_Nice_logo.svg/330px-OGC_Nice_logo.svg.png' },
  { id: 'lens', name: 'Lens', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/RC_Lens_logo.svg/330px-RC_Lens_logo.svg.png' },
  { id: 'rennes', name: 'Rennes', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Stade_Rennais_FC.svg/330px-Stade_Rennais_FC.svg.png' },
  { id: 'reims', name: 'Reims', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/19/Stade_de_Reims_logo.svg/330px-Stade_de_Reims_logo.svg.png' },
  { id: 'strasbourg', name: 'Strasbourg', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Racing_Club_de_Strasbourg_logo.svg/330px-Racing_Club_de_Strasbourg_logo.svg.png' },
  { id: 'nantes', name: 'Nantes', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Logo_FC_Nantes_%28avec_fond%29_-_2019.svg/330px-Logo_FC_Nantes_%28avec_fond%29_-_2019.svg.png' },
  { id: 'montpellier', name: 'Montpellier', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a8/Montpellier_HSC_logo.svg/330px-Montpellier_HSC_logo.svg.png' },
  { id: 'brest', name: 'Brest', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Stade_Brestois_29_logo.svg/330px-Stade_Brestois_29_logo.svg.png' },
  { id: 'toulouse', name: 'Toulouse', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Toulouse_FC_2018_logo.svg/330px-Toulouse_FC_2018_logo.svg.png' },
  { id: 'le-havre', name: 'Le Havre', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Le_Havre_AC_logo.svg/330px-Le_Havre_AC_logo.svg.png' },
  { id: 'angers', name: 'Angers', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Angers_Sporting_Club_de_l%27Ouest_logo.svg/330px-Angers_Sporting_Club_de_l%27Ouest_logo.svg.png' },
  { id: 'auxerre', name: 'Auxerre', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/51/AJAuxerreLogo.svg/330px-AJAuxerreLogo.svg.png' },
  { id: 'saint-etienne', name: 'Saint-Etienne', league: 'Ligue 1', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/25/AS_Saint-%C3%89tienne_logo.svg/330px-AS_Saint-%C3%89tienne_logo.svg.png' },
  { id: 'anderlecht', name: 'Anderlecht', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/R.S.C._Anderlecht.svg/330px-R.S.C._Anderlecht.svg.png' },
  { id: 'antwerp', name: 'Royal Antwerp', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0b/Royal_Antwerp_Football_Club_logo.svg/330px-Royal_Antwerp_Football_Club_logo.svg.png' },
  { id: 'brugge', name: 'Club Brugge', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Club_Brugge_KV_logo.svg/330px-Club_Brugge_KV_logo.svg.png' },
  { id: 'genk', name: 'Genk', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Logo_KRC_Genk.png/330px-Logo_KRC_Genk.png' },
  { id: 'gent', name: 'Gent', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/KAA_Gent_logo.svg/330px-KAA_Gent_logo.svg.png' },
  { id: 'union-sg', name: 'Union Saint-Gilloise', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/0/02/Royale_Union_Saint-Gilloise_logo.png' },
  { id: 'standard', name: 'Standard Liege', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Standard_Li%C3%A8ge_logo.svg/330px-Standard_Li%C3%A8ge_logo.svg.png' },
  { id: 'charleroi', name: 'Charleroi', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/Royal_Charleroi_Sporting_Club_logo.svg/330px-Royal_Charleroi_Sporting_Club_logo.svg.png' },
  { id: 'mechelen', name: 'Mechelen', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/28/KV_Mechelen_logo.svg/330px-KV_Mechelen_logo.svg.png' },
  { id: 'cercle', name: 'Cercle Brugge', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Logo_Cercle_Brugge_2022.png/330px-Logo_Cercle_Brugge_2022.png' },
  { id: 'st-truiden', name: 'Sint-Truiden', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/f/f1/K._Sint-Truidense_V.V._logo.png' },
  { id: 'kortrijk', name: 'Kortrijk', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/KV_Kortrijk_logo_2016.svg/330px-KV_Kortrijk_logo_2016.svg.png' },
  { id: 'ohl', name: 'OH Leuven', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/OH_LEUVEN.png/330px-OH_LEUVEN.png' },
  { id: 'westerlo', name: 'Westerlo', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/1/17/K.V.C._Westerlo_logo.png' },
  { id: 'dender', name: 'Dender', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/9/98/FCVDenderEH.png' },
  { id: 'beerschot', name: 'Beerschot', league: 'Belgian Pro League', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Koninklijke_Beerschot_Voetbalclub_Antwerpen_logo.svg/330px-Koninklijke_Beerschot_Voetbalclub_Antwerpen_logo.svg.png' },
  { id: 'atlanta-united', name: 'Atlanta United', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/81/Atlanta_United_FC_logo.svg/330px-Atlanta_United_FC_logo.svg.png' },
  { id: 'austin-fc', name: 'Austin FC', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/08/Austin_FC_logo.svg/330px-Austin_FC_logo.svg.png' },
  { id: 'charlotte-fc', name: 'Charlotte FC', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Charlotte_FC_logo.svg/330px-Charlotte_FC_logo.svg.png' },
  { id: 'chicago-fire', name: 'Chicago Fire', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Chicago_Fire_FC_logo.svg/330px-Chicago_Fire_FC_logo.svg.png' },
  { id: 'fc-cincinnati', name: 'FC Cincinnati', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/81/FC_Cincinnati_Logo.svg/330px-FC_Cincinnati_Logo.svg.png' },
  { id: 'colorado-rapids', name: 'Colorado Rapids', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Colorado_Rapids_logo.svg/330px-Colorado_Rapids_logo.svg.png' },
  { id: 'columbus-crew', name: 'Columbus Crew', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Columbus_Crew_logo.svg/330px-Columbus_Crew_logo.svg.png' },
  { id: 'dc-united', name: 'D.C. United', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/D.C._United_logo.svg/330px-D.C._United_logo.svg.png' },
  { id: 'fc-dallas', name: 'FC Dallas', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/15/FC_Dallas_logo.svg/330px-FC_Dallas_logo.svg.png' },
  { id: 'houston-dynamo', name: 'Houston Dynamo', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Houston_Dynamo_FC_logo.svg/330px-Houston_Dynamo_FC_logo.svg.png' },
  { id: 'inter-miami', name: 'Inter Miami', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/Inter_Miami_CF_logo.svg/330px-Inter_Miami_CF_logo.svg.png' },
  { id: 'la-galaxy', name: 'LA Galaxy', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Los_Angeles_Galaxy_logo.svg/330px-Los_Angeles_Galaxy_logo.svg.png' },
  { id: 'lafc', name: 'Los Angeles FC', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/Los_Angeles_FC_logo.svg/330px-Los_Angeles_FC_logo.svg.png' },
  { id: 'minnesota-united', name: 'Minnesota United', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Minnesota_United_FC_logo.svg/330px-Minnesota_United_FC_logo.svg.png' },
  { id: 'cf-montreal', name: 'CF Montreal', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/CF_Montr%C3%A9al_logo.svg/330px-CF_Montr%C3%A9al_logo.svg.png' },
  { id: 'nashville-sc', name: 'Nashville SC', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Nashville_SC_logo.svg/330px-Nashville_SC_logo.svg.png' },
  { id: 'new-england', name: 'New England Revolution', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/New_England_Revolution_logo.svg/330px-New_England_Revolution_logo.svg.png' },
  { id: 'nycfc', name: 'New York City FC', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/New_York_City_FC_logo.svg/330px-New_York_City_FC_logo.svg.png' },
  { id: 'new-york-red-bulls', name: 'New York Red Bulls', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/New_York_Red_Bulls_logo.svg/330px-New_York_Red_Bulls_logo.svg.png' },
  { id: 'orlando-city', name: 'Orlando City', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Orlando_City_SC_logo.svg/330px-Orlando_City_SC_logo.svg.png' },
  { id: 'philadelphia-union', name: 'Philadelphia Union', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Philadelphia_Union_logo.svg/330px-Philadelphia_Union_logo.svg.png' },
  { id: 'portland-timbers', name: 'Portland Timbers', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Portland_Timbers_logo.svg/330px-Portland_Timbers_logo.svg.png' },
  { id: 'real-salt-lake', name: 'Real Salt Lake', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/58/Real_Salt_Lake_logo_2005.svg/330px-Real_Salt_Lake_logo_2005.svg.png' },
  { id: 'san-diego-fc', name: 'San Diego FC', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/13/San_Diego_FC_logo.svg/330px-San_Diego_FC_logo.svg.png' },
  { id: 'san-jose-earthquakes', name: 'San Jose Earthquakes', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/San_Jose_Earthquakes_Logo.svg/330px-San_Jose_Earthquakes_Logo.svg.png' },
  { id: 'seattle-sounders', name: 'Seattle Sounders', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Seattle_Sounders_FC.svg/330px-Seattle_Sounders_FC.svg.png' },
  { id: 'sporting-kc', name: 'Sporting Kansas City', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/Sporting_Kansas_City_logo.svg/330px-Sporting_Kansas_City_logo.svg.png' },
  { id: 'st-louis-city', name: 'St. Louis City SC', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2b/St._Louis_City_SC_logo.svg/330px-St._Louis_City_SC_logo.svg.png' },
  { id: 'toronto-fc', name: 'Toronto FC', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/Toronto_FC_Logo.svg/330px-Toronto_FC_Logo.svg.png' },
  { id: 'vancouver-whitecaps', name: 'Vancouver Whitecaps', league: 'MLS', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/95/Vancouver_Whitecaps_FC_logo.svg/330px-Vancouver_Whitecaps_FC_logo.svg.png' },
];

const byId = new Map(teams.map(team => [team.id, team]));

module.exports = { teams, byId };
